### ISSUE TITLE
Cant open chests in Ultima Underworld Unity

### ISSUE THREAD

**Issue by fouriehs** [hankmorgan/UnderworldExporter#51]
First off... HankMorgan, Thank you for the work you put into The ultima underworld 1 unity project. Really amazing. Had a corrupt save. Had to start over. No save issues yet.

2 issues:
- firstly, i can't open chests or barrels. Can't break them either. In the 2nd lvl where the orb is, I  can't access the chest. I'm scared I'm missing out on quest items, etc.

-secondly, when I equip gloves and helmet, they disappear when I click 3 times in the inventory. Very frustrating because the extra armour hells a lot.

The trading glitch is also a bit of a turn off. I can give 1 rock for anything... is there a way to disable that?

I would appreciate the feedback and help. I am now stuck in the game I wanted to play for 20 years...

Please help!?

@hankmorgan

**Comment by fouriehs** [comment]
Update 2019/10/22. My saves just stopped working and cant load. Probably corrupt... hankmorgan please help

**Comment by hankmorgan** [comment]
I'll check these out.

**Comment by lookingglassed** [comment]
I had this problem as well, I will let you know if restart or other fixes work (for both helmet and gloves disappearing and chest near the orb on level 2)

**Comment by fouriehs** [comment]
Hi Thank you for coming back to me. I reverted to playing the original again. Hard to do after Unity version.... Looking forward in hearing  from you. Kind Regards.Hendrik Sent from Mail for Windows 10 From: lookingglassedSent: Thursday, 28 May 2020 14:32To: hankmorgan/UnderworldExporterCc: fouriehs; AuthorSubject: Re: [hankmorgan/UnderworldExporter] Cant open chests in Ultima Underworld Unity (#51) I had this problem as well, I will let you know if restart or other fixes work (for both helmet and gloves disappearing and chest near the orb on level 2)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by hankmorgan** [comment]
I think the chest issue is fixed in code. Should be sorted in the next release build.

**Comment by DaRodus** [comment]
What a joy to have you back in your project. I think it is a great contribution.
There are some key points in UW1 that need to be fixed in order to finish:
1.- The Chests with decisive runes.
2.- That the objects of the inventory stop disappearing or when they are placed in the game.

If those two points are strengthened the game would be quite consistent.

**Comment by fouriehs** [comment]
Hi Hank

 

Please let me know when the next update will be ready. Will wait till then to download.

 

Thanks a lot!

 

Kind Regards,

 

Hendrik Fourie

**Comment by fouriehs** [comment]
Hi Hank

 

Very keen to play this again.

 

Can you point me in the right direction as to where to find the latest release download?

 

Kind Regards,

 



 

From: ***@***.*** ***@***.***> 
Sent: Monday, 09 August 2021 17:03
To: 'hankmorgan/UnderworldExporter' ***@***.***>; 'hankmorgan/UnderworldExporter' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [hankmorgan/UnderworldExporter] Cant open chests in Ultima Underworld Unity (#51)

 

Hi Hank

 

Please let me know when the next update will be ready. Will wait till then to download.

 

Thanks a lot!

 

Kind Regards,

 

Hendrik Fourie

**Comment by hankmorgan** [comment]
The latest code/scene files are at https://github.com/hankmorgan/Underworld-Exporter-Scene
You can clone and run that within Unity however it's in a buggy state and has no saving support.

I'd strongly advise you to play using the original version in Dosbox.  It's still my preferred way to play.  I find a simple rebind of keys in dosbox so that the S key is swapped with the X key makes that version very playable.
